// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFAby_CshO_wgDlxLrATqEoxrE7cK_WnE',
    appId: '1:533012559645:web:bad4ff2381bae39fab13f4',
    messagingSenderId: '533012559645',
    projectId: 'wisdom-portal-a7847',
    authDomain: 'wisdom-portal-a7847.firebaseapp.com',
    storageBucket: 'wisdom-portal-a7847.firebasestorage.app',
    measurementId: 'G-5M4BRD7M7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwiFbo7Ru4Ob_EcMaLNfSfMRsPBOYno8Q',
    appId: '1:533012559645:android:fc2d2b701b955d9eab13f4',
    messagingSenderId: '533012559645',
    projectId: 'wisdom-portal-a7847',
    storageBucket: 'wisdom-portal-a7847.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx-7mPG30OPnAh9dEl_112hPxIUh0Bk-s',
    appId: '1:533012559645:ios:e85a54b5107fc193ab13f4',
    messagingSenderId: '533012559645',
    projectId: 'wisdom-portal-a7847',
    storageBucket: 'wisdom-portal-a7847.firebasestorage.app',
    iosBundleId: 'com.example.wisdomPortal1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFAby_CshO_wgDlxLrATqEoxrE7cK_WnE',
    appId: '1:533012559645:web:8edbc8c2f933cc50ab13f4',
    messagingSenderId: '533012559645',
    projectId: 'wisdom-portal-a7847',
    authDomain: 'wisdom-portal-a7847.firebaseapp.com',
    storageBucket: 'wisdom-portal-a7847.firebasestorage.app',
    measurementId: 'G-Z950769HFD',
  );
}
